In [ ]:
import pandas as pd

df = pd.read_parquet('similar.parquet')
df.set_index('item_id_1', inplace=True)
df

              score  item_id_2
item_id_1
99262      0.946254      99245
99262      0.946169      99254
99262      0.937996      99261
99262      0.927964      99241
99262      0.927211      99247
...             ...        ...
94642241   0.694699   97416291
94642241   0.693174   94905127
94642241   0.687228   97416300
94642241   0.680850   97416286
94642241   0.678054   97416289

[9998092 rows x 2 columns]

In [21]:
df.loc[99263]

              score  item_id_2
item_id_1
99263      0.835172    1437821
99263      0.828107   12979026
99263      0.821217     782551
99263      0.820372   24077668
99263      0.818109   24125914
99263      0.815655     782697
99263      0.815126    1166451
99263      0.808053   12979035
99263      0.807977   23678829
99263      0.807644     952990

In [3]:
item_id = 99262
k = 100

i2i = df.loc[item_id].head(k)
i2i = i2i[["item_id_2", "score"]].to_dict(orient="list")
i2i

{'item_id_2': [99245,
  99254,
  99261,
  99241,
  99247,
  99257,
  99252,
  99239,
  4637878,
  640726],
 'score': [0.9462535977363586,
  0.946168839931488,
  0.9379955530166626,
  0.9279637336730957,
  0.9272109866142273,
  0.9235177636146545,
  0.9084769487380981,
  0.9037085771560669,
  0.8949015140533447,
  0.8822706937789917]}

In [ ]:
interactions = pd.read_parquet('data/interactions.parquet')
interactions

     user_id   track_id  track_seq started_at
0          0      99262          1 2022-07-17
1          0     589498          2 2022-07-19
2          0     590262          3 2022-07-21
3          0     590303          4 2022-07-22
4          0     590692          5 2022-07-22
..       ...        ...        ...        ...
287  1374582   95514767        288 2022-12-29
288  1374582   97220301        289 2022-12-29
289  1374582   97241171        290 2022-12-29
290  1374582   98542641        291 2022-12-29
291  1374582  100736375        292 2022-12-30

[222629898 rows x 4 columns]

In [25]:
interactions[(interactions["user_id"] == 20153)]

     user_id  track_id  track_seq started_at
0      20153  25427167          1 2022-01-27
1      20153  29720940          2 2022-01-27
2      20153  29720949          3 2022-01-28
3      20153  30087865          4 2022-01-29
4      20153  30087871          5 2022-02-01
..       ...       ...        ...        ...
104    20153  80577790        105 2022-11-29
105    20153  81056620        106 2022-12-07
106    20153  81057377        107 2022-12-07
107    20153  81454516        108 2022-12-10
108    20153  81936376        109 2022-12-19

[109 rows x 4 columns]

In [9]:
items = pd.read_parquet('data/items.parquet')
items

,item_id,albums,artists,genres,track_name,artist_names,genre_names
0,26,"[3, 2490753]",[16],"[11, 21]",Complimentary Me,[Elizabeth & the Catapult],"[pop, folk]"
1,38,"[3, 2490753]",[16],"[11, 21]",Momma's Boy,[Elizabeth & the Catapult],"[pop, folk]"
2,135,"[12, 214, 2490809]",[84],[11],Atticus,[Noisettes],[pop]
3,136,"[12, 214, 2490809]",[84],[11],24 Hours,[Noisettes],[pop]
4,138,"[12, 214, 322, 72275, 72292, 91199, 213505, 24...",[84],[11],Don't Upset The Rhythm (Go Baby Go),[Noisettes],[pop]
...,...,...,...,...,...,...,...
999995,101478482,[21399811],[5540395],"[3, 75]",На лицо,[FLESH],"[rusrap, rap]"
999996,101490148,[21403052],[9078726],"[11, 20]",Без капли мысли,[Даня Милохин],"[pop, ruspop]"
999997,101493057,[21403883],[11865715],"[44, 75]",SKITTLES,[WhyBaby?],"[foreignrap, rap]"
999998,101495927,[21404975],[4462686],"[3, 75]",Москва,[Yanix],"[rusrap, rap]"
999999,101521819,[21414638],[5056591],"[3, 75]",Вокзал,[Джарахов],"[rusrap, rap]"

In [15]:
items

,item_id,albums,artists,genres,track_name,artist_names,genre_names
0,26,"[3, 2490753]",[16],"[11, 21]",Complimentary Me,[Elizabeth & the Catapult],"[pop, folk]"
1,38,"[3, 2490753]",[16],"[11, 21]",Momma's Boy,[Elizabeth & the Catapult],"[pop, folk]"
2,135,"[12, 214, 2490809]",[84],[11],Atticus,[Noisettes],[pop]
3,136,"[12, 214, 2490809]",[84],[11],24 Hours,[Noisettes],[pop]
4,138,"[12, 214, 322, 72275, 72292, 91199, 213505, 24...",[84],[11],Don't Upset The Rhythm (Go Baby Go),[Noisettes],[pop]
...,...,...,...,...,...,...,...
999995,101478482,[21399811],[5540395],"[3, 75]",На лицо,[FLESH],"[rusrap, rap]"
999996,101490148,[21403052],[9078726],"[11, 20]",Без капли мысли,[Даня Милохин],"[pop, ruspop]"
999997,101493057,[21403883],[11865715],"[44, 75]",SKITTLES,[WhyBaby?],"[foreignrap, rap]"
999998,101495927,[21404975],[4462686],"[3, 75]",Москва,[Yanix],"[rusrap, rap]"
999999,101521819,[21414638],[5056591],"[3, 75]",Вокзал,[Джарахов],"[rusrap, rap]"

In [18]:
top_popular = pd.read_parquet('data/top_popular.parquet')
top_popular

,item_id,users,recency_score,users_norm,recency_norm,popularity_score,artist_names,genre_names,album_names
0,33311009,99567,38998.842731,0.968230,0.963573,0.965901,[Imagine Dragons],"[rock, allrock]","[Shape Of Pop, NOW That's What I Call Music, E..."
1,65851540,76004,40473.170229,0.739092,1.000000,0.869546,[Dabro],"[pop, ruspop]",[Юность]
2,60292250,74248,40436.725908,0.722015,0.999100,0.860557,[The Weeknd],[rnb],"[Blinding Lights, After Hours, After Hours, Af..."
3,35505245,94291,32436.955774,0.916924,0.801443,0.859183,"[Miyagi & Эндшпиль, Рем Дигга]","[rusrap, rap]","[I Got Love, I Got Love]"
4,51241318,78010,36604.154951,0.758599,0.904405,0.831502,"[Tommee Profitt, Fleurie, Mellen Gi]",[rnb],"[In the End, Christian TikTok, Trending Now 20..."
...,...,...,...,...,...,...,...,...,...
95,93126179,33455,22871.502484,0.325324,0.565103,0.445213,[Люся Чеботина],"[pop, ruspop]",[The End]
96,43731470,47451,17237.143153,0.461428,0.425890,0.443659,[Trevor Daniel],"[pop, foreignrap, rap]","[Falling, Homesick, Shisha Lounge, Falling, Ni..."
97,34735046,49351,16071.382042,0.479904,0.397087,0.438496,[Hippie Sabotage],[electronics],[Providence]
98,69374769,36400,21068.163919,0.353962,0.520546,0.437254,[Fousheé],[rnb],"[Deep End, time machine]"
99,16298499,51656,14824.942151,0.502319,0.366290,0.434305,[Indila],[estrada],"[Dernière Danse, Mini World, Mini World, Reina..."

In [27]:
recs = pd.read_parquet('data/recommendations.parquet')
recs

,user_id,item_id,original_als_score,user_listened_genre_diversity,popularity_score,main_genre,score,rank
0,4,41625041,0.154242,1.000000,0.352477,rock,0.660203,0
1,4,45772994,0.096999,1.000000,0.215883,rock,0.589500,1
2,4,44092998,0.084595,1.000000,0.262439,films,0.574716,2
3,4,51422266,0.085559,1.000000,0.467400,metal,0.512833,3
4,4,60292250,0.139112,1.000000,0.880117,rnb,0.358193,4
...,...,...,...,...,...,...,...,...
63733095,1374582,56312027,0.170637,0.741493,0.418891,pop,0.256304,95
63733096,1374582,62064061,0.105790,0.741493,0.084374,foreignrap,0.232914,96
63733097,1374582,67469457,0.142653,0.741493,0.234140,electronics,0.214863,97
63733098,1374582,52395280,0.146261,0.741493,0.396219,electronics,0.194557,98
63733099,1374582,41325607,0.118348,0.741493,0.214352,pop,0.150310,99

In [29]:
recs[recs["user_id"] == 1374582]

,user_id,item_id,original_als_score,user_listened_genre_diversity,popularity_score,main_genre,score,rank
63733000,1374582,83063895,0.193479,0.741493,0.723316,pop,0.840628,0
63733001,1374582,71308883,0.101911,0.741493,0.475962,pop,0.769377,1
63733002,1374582,66853268,0.125982,0.741493,0.351669,pop,0.735496,2
63733003,1374582,65851540,0.115349,0.741493,0.890227,pop,0.729881,3
63733004,1374582,64496155,0.143904,0.741493,0.505739,pop,0.686687,4
...,...,...,...,...,...,...,...,...
63733095,1374582,56312027,0.170637,0.741493,0.418891,pop,0.256304,95
63733096,1374582,62064061,0.105790,0.741493,0.084374,foreignrap,0.232914,96
63733097,1374582,67469457,0.142653,0.741493,0.234140,electronics,0.214863,97
63733098,1374582,52395280,0.146261,0.741493,0.396219,electronics,0.194557,98
63733099,1374582,41325607,0.118348,0.741493,0.214352,pop,0.150310,99